name: Run Research

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Topic to research"
        required: true
        type: string
      max_sources:
        description: "Max total sources"
        required: false
        default: "12"
      depth:
        description: "Subquestion expansion depth"
        required: false
        default: "2"

permissions:
  contents: write
  pull-requests: write

jobs:
  research:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 👇 Extra diagnostics so we can see what's going on
      - name: Environment & repo snapshot
        run: |
          set -euxo pipefail
          pwd
          python --version
          pip --version
          ls -R
          echo "----- settings.yaml -----"
          cat configs/settings.yaml || true
          echo "-------------------------"

      - name: Install deps (verbose)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt -v
          python - <<'PY'
          import sys
          print("Python:", sys.version)
          import yaml, requests
          import duckduckgo_search, trafilatura
          from slugify import slugify
          print("Imports OK")
          PY

      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euxo pipefail
          python scripts/research.py "${{ inputs.topic }}" \
            --max-sources ${{ inputs.max_sources }} \
            --depth ${{ inputs.depth }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "research: ${{ inputs.topic }}"
          title: "Research: ${{ inputs.topic }}"
          body: |
            Automated research run for **${{ inputs.topic }}**.
          branch: "research/${{ github.run_id }}"
          delete-branch: true
